name: Aiven Wake Up Test

on:
  workflow_dispatch:

jobs:
  wakeup:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Programs every 10 seconds
        run: |
          for i in {1..12}; do
            echo "Request #$i"

            curl --fail --show-error \
              -w "\nHTTP STATUS: %{http_code}\n" \
              "https://lms-8r47.onrender.com/api/auth/getPrograms"

            echo "Waiting 10 seconds..."
            sleep 10
          done
