name: Aiven Wake Up

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  wakeup:
    runs-on: ubuntu-latest

    steps:
      - name: Wake up Render
        run: |
          curl --fail --show-error \
            -w "\nHTTP STATUS: %{http_code}\n" \
            "https://lms-8r47.onrender.com/api/auth/getPrograms"
